[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ImageHashes = "4e842e0a-c737-477c-a320-5a4e4980a4a4"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
